In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pathlib as pl
from collections import defaultdict
from functools import reduce

In [5]:
p = pl.Path('../output/initialw/100-8/iw1-w0.csv')
df = pd.read_csv(p).sort_values('seed')
df = df.rename(columns={'initial_weight': 'initial-weight'})
df = df.set_index('seed')
df = df.assign(dispersion=lambda x: x.desviation/(x.range * 0.5) * 100)
df.head()

,initial-weight,weight,none-anonymity,mean,median,desviation,min,max,range,person1,person5,person10,person15,dispersion
seed,,,,,,,,,,,,,,
0,1,0,0,14.926070,13.0,8.314494,2.333333,35.0,32.666667,27.0,5.2,3.1,3.133333,50.905065
1,1,0,0,14.902643,13.0,8.005542,2.000000,36.0,34.000000,19.0,5.4,3.6,2.466667,47.091424
2,1,0,0,14.960146,13.0,8.350868,2.333333,36.0,33.666667,31.0,6.8,3.7,2.466667,49.609119
3,1,0,0,15.141271,13.5,8.320030,2.000000,37.0,35.000000,28.0,6.0,3.5,2.266667,47.543031
4,1,0,0,14.854851,12.5,8.240634,2.166667,35.0,32.833333,29.0,6.0,3.0,2.533333,50.196758

In [11]:
df.mean().to_frame().transpose()

,initial-weight,weight,none-anonymity,mean,median,desviation,min,max,range,person1,person5,person10,person15,dispersion
0,1.0,0.0,0.0,14.948149,13.285256,8.249086,2.183061,36.634615,34.451554,24.192308,5.678846,3.293269,2.541026,48.110823